import { Inter } from "@next/font/google";
import Head from "next/head";
import Hero from "@/components/Hero";
import Gallery from "@/components/Gallery";
import Location from "@/components/Location";
import Footer from "@/components/Footer";
import About from "@/components/About";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero></Hero>
      <About></About>
      <Gallery></Gallery>
      <Location></Location>
      <Footer></Footer>
    </>
  );
}
